# Generated by Django 5.1.1 on 2025-12-16 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uma_name', models.CharField(max_length=50, verbose_name='賽馬娘名稱')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='稱號')),
                ('rank', models.CharField(max_length=10, verbose_name='評級')),
                ('score', models.PositiveIntegerField(verbose_name='分數')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='等級')),
                ('speed', models.PositiveIntegerField(default=0)),
                ('stamina', models.PositiveIntegerField(default=0)),
                ('power', models.PositiveIntegerField(default=0)),
                ('guts', models.PositiveIntegerField(default=0)),
                ('intelligence', models.PositiveIntegerField(default=0)),
                ('terrain', models.CharField(blank=True, max_length=20, null=True, verbose_name='場地資質')),
                ('distance', models.CharField(blank=True, max_length=20, null=True, verbose_name='距離資質')),
                ('strategy', models.CharField(blank=True, max_length=20, null=True, verbose_name='腳質資質')),
                ('portrait', models.ImageField(blank=True, null=True, upload_to='uma/portraits/', verbose_name='頭像圖片')),
                ('unique_skills', models.JSONField(blank=True, default=list)),
                ('gold_skills', models.JSONField(blank=True, default=list)),
                ('white_skills', models.JSONField(blank=True, default=list)),
                ('blue_skills', models.JSONField(blank=True, default=list)),
                ('red_skills', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '育成結果',
                'verbose_name_plural': '育成結果',
            },
        ),
    ]
