# Generated by Django 5.1.1 on 2025-12-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingresult',
            name='portrait_crop',
            field=models.ImageField(blank=True, null=True, upload_to='uma/portrait_crop/'),
        ),
    ]
