# Generated by Django 5.1.1 on 2025-12-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uma', '0002_trainingresult_portrait_crop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingresult',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='uma/screenshots/', verbose_name='訓練截圖'),
        ),
    ]
